/**
 * Generated by `npm run fonts` (scripts/build-fonts.mjs) — DO NOT EDIT BY HAND.
 *
 * The character set the committed webfont subsets in `public/fonts/` cover, and
 * the measured facts about them. `tests/unit/font-charset.test.ts` re-derives the
 * set from `src/` and fails if the two disagree, which is the signal to re-run
 * the script.
 */

/** Every character the committed subsets were cut for, ordered by codepoint. */
export const FONT_CHARSET = " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ ¡¢£¤¥¦§¨©ª«¬­®¯°±²³´µ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõö÷øùúûüýþÿĀāĂăĄąĆćĈĉĊċČčĎďĐđĒēĔĕĖėĘęĚěĜĝĞğĠġĢģĤĥĦħĨĩĪīĬĭĮįİıĲĳĴĵĶķĸĹĺĻļĽľĿŀŁłŃńŅņŇňŉŊŋŌōŎŏŐőŒœŔŕŖŗŘřŚśŜŝŞşŠšŢţŤťŦŧŨũŪūŬŭŮůŰűŲųŴŵŶŷŸŹźŻżŽžſΘπ–—’“”•…⁰ⁿ₂←→↔↩⇒⇔∅−≈≤≥⋯⌀─▁▲▶▼✓✕✗";

/**
 * Characters NEITHER committed face draws, so the reader's system font supplies
 * them. All of them are geometric markers the site has always set in the system
 * stack (visualizer carets, the delete mark, null/empty symbols, the legend's
 * comparing and range swatches, the superscript in `O(2ⁿ)`), so self-hosting
 * did not move them. A new entry here is a decision to make, not a fact to
 * absorb — redraw it as SVG, swap it for a covered character, or accept it.
 */
export const FONT_FALLBACK_GLYPHS = "ⁿ⇒⇔∅⋯⌀▲▶▼✕✗";

/** Measured byte size of each committed subset. A claim about the build, measured. */
export const FONT_BYTES: Record<string, number> = {
  "plex-sans.woff2": 60020,
  "plex-mono.woff2": 17684
};

/**
 * Fallback metric overrides, measured against Arial / Helvetica / Liberation Sans in the
 * shaping engine — these are what buy CLS 0 while the webfont loads. Mirrored
 * into the `@font-face` blocks in `src/styles/tokens.css`; keep the two in sync.
 */
export const FONT_FALLBACK_METRICS = {
  "plex-sans.woff2": {
    "sizeAdjust": "101.82%",
    "ascentOverride": "101.16%",
    "descentOverride": "27.50%"
  },
  "plex-mono.woff2": {
    "sizeAdjust": "128.42%",
    "ascentOverride": "80.20%",
    "descentOverride": "21.80%"
  }
} as const;
